### ISSUE TITLE
3.0.1 does not build or start

### ISSUE THREAD

**Issue by chwba** [primefaces/sigma-react#21]
Upon downloading the latest release (3.0.1) and doing npm install we get:

```
npm ERR! code 1
npm ERR! path C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\chwba\\Git\\sigma-react-3.0.1\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.4.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\chwba\Git\sigma-react-3.0.1\venv\Scripts\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\chwba\Git\sigma-react-3.0.1\venv\Scripts\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:453:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:662:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chwba\\Git\\sigma-react-3.0.1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--lib
sass_library="
npm ERR! gyp ERR! cwd C:\Users\chwba\Git\sigma-react-3.0.1\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.4.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chwba\AppData\Local\npm-cache\_logs\2021-07-05T15_40_18_097Z-debug.log
```

**Comment by mcandu** [comment]
Using recommended version of node, instead of last version of it, will solve this issue.
